FROM --platform=linux/amd64 python:3.9-slim-buster  as test-streamlit-build
LABEL authors="nbiggs112"

WORKDIR /app

COPY streamlit-requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY mystreamlitapp.py app.py

EXPOSE 8501

CMD [ "python3", "-m" , "streamlit", "run", "app.py"]
